services:
  producer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: producer
    command: ["python", "producer.py"]
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka1:29092  
    networks:
      - kafka_net_kafka_nifi  

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: consumer
    command: ["python", "consumer.py"]
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka1:29092  
    networks:
      - kafka_net_kafka_nifi  

  anomaly-detector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anomaly-detector
    command: ["python", "anomalies_traitement.py"]
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka1:29092  
      ELASTICSEARCH_HOST: elasticsearch:9200  
    volumes:
      - ./normal_data:/app/normal_data
    networks:
      - kafka_net_kafka_nifi  
      - elasticsearch_net_es  

networks:
  kafka_net_kafka_nifi:
    external: true  
  elasticsearch_net_es:
    external: true  